/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kollasuyo.archer.Jefe;

import EstructuraDatos.ListaDispositivos;
import EstructuraDatos.NodoDispositivo;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import kollasuyo.archer.Emeplado.InicioEmpleado;
import kollasuyo.archer.GenradorCodigoRegistro;
import kollasuyo.archer.Inventario.dispositivo;
import kollasuyo.archer.Inventario.inventario;
import kollasuyo.archer.Personal.Jefe;

/**
 *
 * @author victo
 */
public class InterInventario extends javax.swing.JFrame {
    DefaultTableModel modelo;
    String trabajo="";
    /**
     * Creates new form Facruta
     */
    
    Jefe j;
    public void setJefe(Jefe j){
        this.j = j;
    }
    
    
    public void Desactivar(){
        this.Cant.enable(false);
        this.Gama.enable(false);
        this.Marca.enable(false);
        this.Modelo.enable(false);
        this.Precio.enable(false);
        this.finalizar.enable(false);
    }
    
    public void Activar(){
        this.Cant.enable(true);
        this.Gama.enable(true);
        this.Marca.enable(true);
        this.Modelo.enable(true);
        this.Precio.enable(true);
        this.finalizar.enable(true);
        
        
        
    }
    
    dispositivo disp;
    inventario inv = new inventario();
    String[] info = new String[6];
    ListaDispositivos ls = new ListaDispositivos();
    
    public void CargarTabla(){        
        inv.Recuperar();
        if(inv.getLs()!=null){
            ls = inv.getLs();
            NodoDispositivo nodo = new NodoDispositivo();
            nodo = ls.getP();
            while(nodo!=null){
                disp = nodo.getDispo();
                info[0] = disp.getId();
                info[1] = String.valueOf(disp.getCantidad());
                info[2] = disp.getNombre();
                info[3] = disp.getGama();
                info[4] = disp.getMarca();
                info[5] = String.valueOf(disp.getPrecioBase());                
                System.out.println(info[0]+"  "+info[1]+"  "+info[2]+"   "+info[3]+"   "+info[4]+" "+info[5]);
                modelo.addRow(info);
                nodo = nodo.getSig();
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"No existen dispositivos registrados");
        }
            
       
    }   
    FondoPanel fondo = new FondoPanel();
    
    
    public InterInventario() {
         this.setContentPane(fondo);
        initComponents();
        SpinnerNumberModel mn = new SpinnerNumberModel();
        mn.setMinimum(0);
        this.Cant.setModel(mn);
        Desactivar();
        setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Modelo");
        modelo.addColumn("Gama");
        modelo.addColumn("Marca");
        modelo.addColumn("Precio");
        this.tabla.setModel(modelo);
        CargarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        modificar = new javax.swing.JToggleButton();
        agregar = new javax.swing.JToggleButton();
        eliminar = new javax.swing.JToggleButton();
        regresar = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        Cant = new javax.swing.JSpinner();
        Modelo = new javax.swing.JTextField();
        Gama = new javax.swing.JTextField();
        Marca = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        finalizar = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Modelo :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("INVENTARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 210, 40));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Modelo", "Gama", "Marca", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, 678, 265));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 91, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Modelo :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 91, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Gama :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 91, -1));

        id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 320, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Precio :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 73, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Marca :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 69, -1));

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 341, 93, 31));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 341, 93, 31));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 341, 93, 31));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 532, 96, 63));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 395, 421, 12));
        getContentPane().add(Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 56, 24));
        getContentPane().add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 157, 24));
        getContentPane().add(Gama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 157, 24));
        getContentPane().add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 157, 24));

        Precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioKeyTyped(evt);
            }
        });
        getContentPane().add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 157, 24));

        finalizar.setText("FInalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 93, 31));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Resgistrar Nuevos Dispostivos");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 383, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:
        if("agregar".equals(trabajo)){
        disp = new dispositivo(this.id.getText(), this.Marca.getText(),this.Gama.getText(),Integer.parseInt(this.Cant.getValue().toString()),Double.parseDouble(this.Precio.getText()), this.Modelo.getText());
        ls.adifinal(disp);
        inv.Guardar();                  
         info[0] = this.id.getText();
                info[1] = String.valueOf(disp.getCantidad());
                info[2] = disp.getNombre();
                info[3] = disp.getGama();
                info[4] = disp.getMarca();
                info[5] = String.valueOf(disp.getPrecioBase());                
                System.out.println(info[0]+"  "+info[1]+"  "+info[2]+"   "+info[3]+"   "+info[4]+" "+info[5]);
                modelo.addRow(info);
        }
        if("modificar".equals(trabajo)){
        
            dispositivo disp = new dispositivo(this.id.getText(), this.Marca.getText(),this.Gama.getText(),(int)this.Cant.getValue(),Double.parseDouble(this.Precio.getText()),this.Modelo.getText());
            ls.Modificar(this.id.getText(), disp);
            inv.Guardar();
            int fila = tabla.getSelectedRow();
            tabla.setValueAt(this.id.getText(),fila,0);
            tabla.setValueAt(this.Cant.getValue(),fila,1);
            tabla.setValueAt(this.Modelo.getText(),fila,2);
            tabla.setValueAt(this.Gama.getText(),fila,3);
            tabla.setValueAt( this.Marca.getText(),fila,4);
            tabla.setValueAt(this.Precio.getText(),fila,5);
            
        }
               
        this.id.setText("");
                this.Gama.setText("");
                this.Marca.setText("");
                this.Modelo.setText("");
                this.Precio.setText("");
                Desactivar();
        
        
                
    }//GEN-LAST:event_finalizarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        inv.setLs(ls);
        inv.Guardar();
        
        InicioJefe ini = new InicioJefe();
        ini.Jefe(j);
        ini.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_regresarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        trabajo = "agregar";
        GenradorCodigoRegistro gen = new GenradorCodigoRegistro();
        String id = gen.generarCodigo();
        this.id.setText(id);
        Activar();
        JOptionPane.showMessageDialog(null,"Ingrese los datos del dispositivo");
        this.Gama.setText(" ");
        this.Marca.setText(" ");
        this.Modelo.setText(" ");
        this.Precio.setText(" ");
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        int fila = tabla.getSelectedRow();
        
        if(fila>=0){
            
            String id = tabla.getValueAt(fila,0).toString();
            ls.eliminar(id);
            inv.setLs(ls);
            inv.Guardar();
            
            modelo.removeRow(fila);            
        }
        else{
            JOptionPane.showMessageDialog(null,"Seleccionar Fila");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        trabajo = "modificar";
        int fila = tabla.getSelectedRow();
        if(fila>=0){
            Activar();
            this.id.setText(tabla.getValueAt(fila,0).toString());
            this.Cant.setValue(Integer.parseInt(tabla.getValueAt(fila,1).toString()));
            this.Gama.setText(tabla.getValueAt(fila,3).toString());
            this.Marca.setText(tabla.getValueAt(fila,4).toString());
            this.Modelo.setText(tabla.getValueAt(fila,2).toString());
            this.Precio.setText(tabla.getValueAt(fila,5).toString());
            
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Seleccione un elemento de la tabla");
        }
        
        
        
    }//GEN-LAST:event_modificarActionPerformed

    private void PrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_PrecioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Cant;
    private javax.swing.JTextField Gama;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Modelo;
    private javax.swing.JTextField Precio;
    private javax.swing.JToggleButton agregar;
    private javax.swing.JToggleButton eliminar;
    private javax.swing.JToggleButton finalizar;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton modificar;
    private javax.swing.JToggleButton regresar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
   class FondoPanel extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Img/Fondo-0.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
        
    }
}
